In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **BASIC OPERATIONS**

In [2]:
import numpy as np

In [3]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [4]:
#Array (in numpy we can store multi-dimentional array)

print('1D Array')
a = np.array([1,2,3,4,5])
print(a)

print('2D Array')
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

print('3D Array')
c = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
type(a)

numpy.ndarray

In [6]:
#SIZE (it gives us the number of elements)

print(a.size)
print(b.size)
print(c.size)

5
10
15


In [7]:
#SHAPE (it gives us number of rows and columns)

print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [8]:
#DATATYPES (it gives us the type of data present in array)

print(a.dtype)
print(b.dtype)
print(c.dtype)



int64
int64
int64


In [9]:
d= np.array([[1,2,3.3,4,5.5],[6.1,7,8,9.5,10],[11,12,13.5,14.7,15]])
print(d.dtype)

float64


In [10]:
# arr.transpose (it replace rows into column & column into rows)

d.transpose()


array([[ 1. ,  6.1, 11. ],
       [ 2. ,  7. , 12. ],
       [ 3.3,  8. , 13.5],
       [ 4. ,  9.5, 14.7],
       [ 5.5, 10. , 15. ]])

# np.ones, np.zeros, np.empty functions

In [11]:
# np.empty((tuple), dtype)

np.empty((4,4), dtype = int)

array([[94904915590352,              0,   489626271861,   433791696995],
       [  498216206368,   468151435365,   476741369968,   416611827826],
       [  450971566194,   519691042924,   502511173664,   416611827822],
       [  416611827830,   463856468073,   420906795105,   433791697004]])

In [12]:
np.empty((4,4), dtype = float)

array([[4.68892585e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

In [13]:
# np.ones((rows,cols), dtype)

x = np.ones(8)
x

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
y = np.ones((5,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
z = np.ones((4,3), dtype = int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
# np.zeros((rows, cols), dtype)

x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [17]:
y = np.zeros((4,6))
y

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
z = np.zeros((3,6), dtype = int)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
z = np.ones((4,5), dtype = str)
z

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [20]:
y = np.ones((3,7), dtype = bool)
y

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [21]:
z = np.zeros((4,5), dtype = str)
z

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [22]:
y = np.zeros((3,7), dtype = bool)
y

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

# ADVANCED FUNCTIONS (np.arange(), np.flatten(), np.ravel(), np.reshape())

### It use in every data analysis & when we need to give axis in Matplotlib

In [23]:
# np.arange(start,end,step)---- its like for loop, but here we are giving 3 parameters:-

a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
##odd number

a = np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [25]:
##even number

a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [26]:
# Reshape
##arr.reshape((rows, cols))

a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [28]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [29]:
##inverse process of reshape i,e single row & multi cols
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# ARRAY SLICING OPERATIONS

In [31]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [32]:
##SLICING

a[0]

array([1, 2, 3, 4, 5])

In [33]:
a[2]

array([11, 12, 13, 14, 15])

In [34]:
a[3]

array([16, 17, 18, 19, 20])

In [35]:
a[0,0]

1

In [36]:
a[3,4] #3rd row & 4th element

20

In [37]:
a[2:5]  #2nd row to 4th row bcoz 5th will not appear

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
a[0:10]  # print all rows & cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [39]:
a[:, 2]  # (:) means all the rows & (2) means the 2nd col

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [40]:
a[2:5, 4]  # 2:5 means 2nd row to 5th row & 4 means from the 4th col

array([15, 20, 25])

In [41]:
a[:,:]  # all row & cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [42]:
a[:,2:5]  # all rows & 2:5 means 2nd col to 4th col

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [43]:
a[:,2:5].dtype  # define the datatype

dtype('int64')

 # MATHEMATICAL OPERATIONS

In [44]:
#To see the Mathematical operations, we need to define 2 arrays

a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [45]:
a+b  # it will add vertically i.e 0+20,1+21--------

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [46]:
np.add(a,b) #this is the function of addition

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [47]:
a-b  # subtract each and every element to each other

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [48]:
np.subtract(a,b)  #this is the function of subtraction

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [49]:
a*b  #multiply by vertically

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [50]:
np.multiply(a,b)  #this is the function of multiply

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [51]:
a/b  #it will give the float result

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [52]:
np.divide(a,b)  #this is the function of dividw

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

# # # #metrix multiplication start from here

In [53]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [ ]:
print(a.shape)
print(b.shape)

In [ ]:
b = b.reshape((3,6))
b

In [ ]:
a@b #here cross multiplication will happen

In [ ]:
a.dot(b) #this is the function of above multiplication with @

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
b.argmax()  #it will give us the index no. of the max value

In [ ]:
np.sum(b)  #sum of all elements in b

In [ ]:
np.sum(b, axis = 1)  #axis = 1 means row , there it will give us sum of each & every row

In [ ]:
np.sum(b, axis = 0)  #axis = 0 means cols, there it will give us sum of each & every cols 

In [ ]:
np.mean(b)

In [ ]:
np.sqrt(b)

In [ ]:
np.std(b)

In [ ]:
np.log(b)

# TRIGONOMETRIC OPERATIONS

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [ ]:
np.pi

In [ ]:
##Sin 90 Degree

np.sin(np.pi/2)

In [ ]:
##Sin 30 Degree

np.sin(np.pi/6)

In [ ]:
##Cos 90 Degree

np.cos(np.pi/2)

In [ ]:
##Cos 30 Degree

np.cos(np.pi/6)

In [ ]:
##Tan 90 Degree

np.tan(np.pi/2)

In [ ]:
np.tan(0)

**###Using Matplotlib with Numpy:--******

In [ ]:
x = np.arange(1,11)
y = np.arange(10, 110, 10)

plt.figure(figsize = (6,6))
plt.plot(x,y, 'r--')
plt.show()

**##Plotting Trignometric Curves**

In [ ]:
##SIN CURVE

x_sin = np.arange(0,2*np.pi, 0.1)
y_sin = np.sin(x_sin)

print(y_sin)

In [ ]:
plt.figure(figsize = (6,6))
plt.plot(x_sin, y_sin)
plt.title('Sin Curve')
plt.show()

In [ ]:
x_cos = np.arange(0,2*np.pi, 0.1)
y_cos = np.cos(x_cos)

print(y_cos)

plt.figure(figsize = (6,6))
plt.plot(x_cos, y_cos)
plt.title('Cos Curve')
plt.show()

In [ ]:
x_tan = np.arange(0,2*np.pi, 0.1)
y_tan = np.tan(x_tan)
print(y_tan)

plt.figure(figsize = (6,6))
plt.plot(x_tan, y_tan)
plt.title('Tan Curve')
plt.show()

In [ ]:
x_cot = np.arange(0, 2*np.pi, 0.1)
y_cot = 1/np.tan(x_cot)
print(y_cot)

plt.figure(figsize = (6,6))
plt.plot(x_cot, y_cot)
plt.title('Cot Curve')
plt.show()
    

**##SUBPLOT**  (all curves should be in one plot)

In [ ]:
plt.figure(figsize =(8,8))

plt.subplot(2,2,1)
plt.plot(x_sin, y_sin, 'r--')
plt.title('Sin Curve')

plt.subplot(2,2,2)
plt.plot(x_cos, y_cos, 'b--')
plt.title('Cos Curve')

plt.subplot(2,2,3)
plt.plot(x_tan, y_tan, 'y--')
plt.title('Tan Curve')

plt.subplot(2,2,4)
plt.plot(x_cot, y_cot, 'g--')
plt.title('Cot Curve')

plt.show()

# # RANDOM OPERATIONS

In [ ]:
np.random.random(1)

In [ ]:
np.random.random(2)

In [ ]:
np.random.random((2,2))

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(1,10, (2,2))

In [ ]:
np.random.randint(1,10, (3,4,5))

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randn(2,5)

In [ ]:
a = np.arange(1,10)
print(a)

In [ ]:
np.random.choice(a)

# STRING OPERATIONS

**#Strings with Numpy library**

In [ ]:
s1 = 'Hoshangi is my Name'
s2 = 'I am the wife of Hardik'

In [ ]:
np.char.add(s1,s2)

In [ ]:
np.char.upper(s1)

In [ ]:
np.char.lower(s1)

In [ ]:
np.char.split(s2)

In [ ]:
s3 = 'Hoshangi is my \nname'
np.char.splitlines(s3)

In [ ]:
np.char.replace(s1,'Name','Sirname')

In [ ]:
print(np.char.center('NUMPY COMPLETED', 80, '*'))